sudo: false
language: node_js
dist: trusty
node_js:
  - "8"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox
cache:
  directories:
    - node_modules
    - eslint-cache
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "npm test"
